vault:
    host: ~
    port: 8200
    roles:
        vpn: ~
        api: ~
        cron: ~
    paths:
        kv: kv/meerkat
        pki: pki/meerkat
    ca:
        secretName: ~
        key: vault.ca

dns:
    domain: ~
    subdomains:
        vpn: vpn
        api: meerkat

postgres:
    host: ~
    port: 5432
    database: meerkat
    credentials:
        type: static # one of ['static', 'vault']
        username: ~
        password: ~
        vaultPath: ~

rbac:
    create: false

vpn:
    serviceAccountName: meerkat-vpn
    podAnnotations: {}
    image:
        name: borchero/meerkat-vpn
        tag: ${CIRCLE_TAG}
        pullPolicy: IfNotPresent
    config:
        redirectGateway: false
        auth: SHA384
        cipher: AES-256-GCM
        routes:
        -   subnet: 10.0.0.0
            mask: 255.0.0.0
        nameservers:
        -   8.8.8.8
        -   8.8.4.4
    service:
        type: LoadBalancer
        protocol: UDP
        port: 1194
        nodePort: 31194
    dns:
        enabled: false
        zones: []
        ip:
            kind: serviceIP
            nodeLabels: {}

api:
    serviceAccountName: meerkat-api
    podAnnotations: {}
    image:
        name: borchero/meerkat-api
        tag: ${CIRCLE_TAG}
        pullPolicy: IfNotPresent
    service:
        type: ClusterIP
        port: 3000
    ingress:
        enabled: false
        auth:
            enabled: true
            # default 'admin:admin' as generated by `htpasswd -nb <user> <password>`
            users: 
            -   admin:$apr1$jOC8q/Sl$Rk/1KEAOupqvHcxp/OkzH0
        entrypoints:
        -   websecure
    dns:
        enabled: false
        zones: []
        tls:
            issuer:
                kind: ~
                name: ~

cron:
    serviceAccountName: meerkat-vpn-cron
    podAnnotations: {}
    image:
        name: borchero/meerkat-cron
        tag: ${CIRCLE_TAG}
        pullPolicy: IfNotPresent
