---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: {{ .Release.Name }}-vpn

spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ .Release.Name }}-vpn

    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ .Release.Name }}-vpn
            annotations:
                vault.hashicorp.com/agent-inject: "true"
                {{ $cn := .Values.openvpn.config.host }}
                {{- with .Values.openvpn.vault }}
                vault.hashicorp.com/role: {{ .role }}

                vault.hashicorp.com/agent-inject-secret-shared-dh.pem: {{ .dh }}
                vault.hashicorp.com/agent-inject-template-shared-dh.pem: |
                    {{ include "vault.kv-value" .dh }}
                vault.hashicorp.com/agent-inject-secret-shared-ta.key: {{ .ta }}
                vault.hashicorp.com/agent-inject-template-shared-ta.key: |
                    {{ include "vault.kv-value" .ta }}

                vault.hashicorp.com/agent-inject-secret-server.crt: {{ .pki.issuer }}
                vault.hashicorp.com/agent-inject-template-server.crt: |
                    {{ $data := dict "secret" .pki.issuer "cn" $cn "out" "certificate" }}
                    {{ include "vault.pki" $data }}
                vault.hashicorp.com/agent-inject-secret-server.key: {{ .pki.issuer }}
                vault.hashicorp.com/agent-inject-template-server.key: |
                    {{ $data := dict "secret" .pki.issuer "cn" $cn "out" "private_key" }}
                    {{ include "vault.pki" $data }}
                vault.hashicorp.com/agent-inject-secret-ca.crt: {{ .pki.issuer }}
                vault.hashicorp.com/agent-inject-template-ca.crt: |
                    {{ $data := dict "secret" .pki.issuer "cn" $cn "out" "issuing_ca" }}
                    {{ include "vault.pki" $data }}

                vault.hashicorp.com/agent-inject-secret-crl.pem: {{ .pki.crl }}
                {{- end }}

        spec:
            serviceAccountName: {{ .Values.openvpn.serviceAccountName }}
            containers:
            -   name: vpn
                image: {{ .Values.openvpn.image.name }}:{{ .Values.openvpn.image.tag }}
                imagePullPolicy: {{ .Values.openvpn.image.pullPolicy }}
                args: ["openvpn", "--config", "/etc/openvpn/server.conf"]
                securityContext:
                    capabilities:
                        add: ["NET_ADMIN"]
                ports:
                -   name: openvpn
                    containerPort: 1194
                    protocol: {{ .Values.openvpn.service.protocol }}
                volumeMounts:
                -   name: server-config
                    mountPath: /etc/openvpn
                    readOnly: true

            volumes:
            -   name: server-config
                configMap:
                    name: {{ .Release.Name }}-vpn-conf
