{{- if .Values.api.dns.enabled }}
---
apiVersion: switchboard.borchero.com
kind: DNSRecord

metadata:
    name: {{ .Release.Name }}-api

spec:
    hosts: ["{{ .Values.api.dns.subdomain }}"]
    tls:
        certificateName: {{ .Release.Name }}-api
        secretName: {{ .Release.Name }}-api-tls
        issuer:
            kind: {{ .Values.api.dns.tls.issuer.kind }}
            name: {{ .Values.api.dns.tls.issuer.name }}
    zones:
    {{- range $i, $val := .Values.api.dns.zones }}
    -   name: {{ $val }}
    {{- end }}
{{- end }}

{{- if .Values.openvpn.dns.enabled }}
---
apiVersion: switchboard.borchero.com
kind: DNSRecord

metadata:
    name: {{ .Release.Name }}-vpn

spec:
    hosts: ["{{ .Values.openvpn.dns.subdomain }}"]
    zones:
    -   name: {{ .Values.openvpn.dns.zone }}
        {{- if eq .Values.openvpn.dns.ip.kind "serviceIP" }}
        serviceIP:
            name: {{ .Release.Name }}-vpn
            namespace: {{ .Release.Namespace }}
            type: ExternalIP
        {{- else if eq .Values.openvpn.dns.ip.kind "nodeIP" }}
        nodeIP:
            matchLabels:
                {{- toYaml .Values.openvpn.dns.ip.nodeLabels | indent 12 }}
            type: ExternalIP
        {{- end }}

{{- end }}
