{{- if eq .Values.postgres.credentials.type "static" -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-api-db-credentials

stringData:
  db-credentials: |
    postgres://{{ required "postgres username required" .Values.postgres.credentials.username }}:{{ required "postgres password required" .Values.postgres.credentials.password }}@{{ required "database host required" .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
{{- end -}}
