version: 2.1

jobs:
  lint-chart:
    docker:
    - image: alpine/helm:3.2.4
    steps:
      - checkout
      - run: deploy/tests/lint.sh

  upload-chart:
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - run: |
          apk add --no-cache gettext

          cd ..
          git clone git@github.com:borchero/helm-charts.git

          export DEST=helm-charts/charts/meerkat@${CIRCLE_TAG}
          mv project/deploy/chart ${DEST}

          envsubst < ${DEST}/values.yaml > ${DEST}/values.subst.yaml
          mv ${DEST}/values.subst.yaml ${DEST}/values.yaml

          envsubst < ${DEST}/Chart.yaml > ${DEST}/Chart.subst.yaml
          mv ${DEST}/Chart.subst.yaml ${DEST}/Chart.yaml

          cd helm-charts
          git config user.name "circleci"
          git config user.email "noreply@borchero.com"
          git add .
          git commit -m "Update Charts"
          git push origin master

workflows:
  version: 2
  deploy:
    jobs:
      - lint-chart
      - upload-chart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
