---
apiVersion: v1
kind: ConfigMap

metadata:
    name: {{ .Release.Name }}-api-env

data:
    DB_CONNECTION_FILE: /vault/secrets/db-credentials

    VAULT_SCHEME: https
    VAULT_HOST: {{ .Values.vault.host }}
    VAULT_PORT: {{ .Values.vault.port | quote }}
    VAULT_PKI: {{ .Values.vault.paths.pki }}
    VAULT_TLS_AUTH: {{ .Values.vault.paths.kv }}/data/tls-auth
    VAULT_TOKEN_FILE: /vault/secrets/token

    VPN_DEVICE: tun
    VPN_HOST: {{ .Values.dns.subdomains.vpn }}.{{ .Values.dns.domain }}
    VPN_PORT: {{ include "vpn.port" .Values.vpn.service }}
    VPN_PROTOCOL: {{ .Values.vpn.service.protocol | lower }}
    VPN_AUTH: {{ .Values.vpn.config.auth }}
    VPN_CIPHER: {{ .Values.vpn.config.cipher }}

---
apiVersion: v1
kind: ConfigMap

metadata:
    name: {{ .Release.Name }}-vpn-conf

data:
    server.conf: |
        user nobody
        group nogroup

        status /tmp/openvpn.log
        explicit-exit-notify 1

        server 192.168.255.0 255.255.255.0
        port 1194
        proto {{ .Values.vpn.service.protocol | lower }}
        dev tun0

        cert /vault/secrets/certificate
        key /vault/secrets/private_key
        ca /vault/secrets/issuing_ca
        dh /vault/secrets/dh-params
        tls-crypt /vault/secrets/tls-auth
        crl-verify /vault/secrets/crl

        auth {{ .Values.vpn.config.auth }}
        cipher {{ .Values.vpn.config.cipher }}

        keepalive 10 60
        key-direction 0
        persist-key
        persist-tun
        verb 3

        compress lz4-v2
        push "compress lz4-v2"
        push "comp-lzo no"

        push "route 192.168.255.0 255.255.255.0"
        push "route 10.0.0.0 255.0.0.0"
        push "dhcp-option DNS 8.8.8.8"
        push "dhcp-option DNS 8.8.4.4"

        {{- if .Values.vpn.config.tunnelAllTraffic }}
        push "redirect-gateway def1"
        {{- end }}
