vault:
    host: ~
    port: 8200
    roles:
        vpn: ~
        api: ~
    paths:
        kv: kv/meerkat
        pki: pki/meerkat
        database: ~

dns:
    domain: ~
    subdomains:
        vpn: vpn
        api: meerkat

postgres:
    host: ~
    port: 5432
    database: meerkat

rbac:
    create: false

vpn:
    serviceAccountName: meerkat-vpn
    image:
        name: borchero/meerkat-vpn
        tag: 0.1.0
        pullPolicy: IfNotPresent
    config:
        tunnelAllTraffic: false
        auth: SHA384
        cipher: AES-256-GCM
    service:
        type: LoadBalancer
        protocol: UDP
        port: 1194
        nodePort: 31194
    dns:
        enabled: false
        zones: []
        ip:
            kind: serviceIP
            nodeLabels: {}

api:
    serviceAccountName: meerkat-api
    image:
        name: borchero/meerkat-api
        tag: 0.1.0
        pullPolicy: IfNotPresent
    service:
        type: ClusterIP
        port: 3000
    ingress:
        enabled: false
        auth:
            enabled: true
            # default 'admin:admin' as generated by `htpasswd -nb <user> <password>`
            users: 
            -   admin:$apr1$jOC8q/Sl$Rk/1KEAOupqvHcxp/OkzH0
        entrypoints:
        -   websecure
    dns:
        enabled: false
        zones: []
        tls:
            issuer:
                kind: ~
                name: ~
